name: travel_app
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  path_provider: ^2.0.5
  rxdart: ^0.27.2
  firebase_core: ^1.6.0
  firebase_auth: ^3.1.1
  cloud_firestore: ^2.5.3
  url_launcher: ^6.0.3
  geocoding: ^2.0.1
  location: ^4.3.0
  geolocator: ^7.6.2
  permission_handler: ^8.1.6


dev_dependencies:
  pedantic: ^1.11.1
  effective_dart: ^1.3.2
  analyzer: ^2.3.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - fonts/
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-Bold.ttf

