name: travel_app
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  path_provider: ^2.0.1
  rxdart: ^0.26.0
  firebase_core: ^1.1.1
  firebase_auth: ^1.1.4
  cloud_firestore: ^2.1.0
  url_launcher: ^6.0.3
  geocoding: ^2.0.0
  location: ^4.1.1

dev_dependencies:
  pedantic: ^1.9.2
  effective_dart: ^1.2.4
  analyzer: ^0.39.17
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - fonts/
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-Bold.ttf

